import { StyleSheet } from 'react-native';
import { fonts } from '../../theme/typography';
export default StyleSheet.create({
  backdrop: { flex: 1, backgroundColor: 'rgba(0,14,34,0.55)' },
  modalPosition: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 12 },
  sheet: { width: '100%', maxWidth: 540, maxHeight: '94%', flexShrink: 1, backgroundColor: '#fff', borderRadius: 28, overflow: 'hidden', borderWidth: 1, borderColor: 'rgba(0,20,46,0.10)', boxShadow: '0px 20px 50px rgba(0,20,46,0.22)' },
  importSheet: { maxWidth: 768 },
  header: { padding: 18, flexDirection: 'row', alignItems: 'center', gap: 12, borderBottomWidth: 1, borderBottomColor: 'rgba(0,20,46,0.08)' },
  headerCopy: { flex: 1, minWidth: 0 },
  headerIcon: { width: 40, height: 40, borderRadius: 12, backgroundColor: '#00142E', alignItems: 'center', justifyContent: 'center' },
  eyebrow: { fontFamily: fonts.bold, fontSize: 9, letterSpacing: 1.5, color: '#0562D2', marginBottom: 4 },
  title: { fontFamily: fonts.bold, fontSize: 19, color: '#00142E' },
  importTitle: { fontFamily: fonts.title, fontSize: 30, lineHeight: 35, textTransform: 'uppercase' },
  close: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#F0F2F5', alignItems: 'center', justifyContent: 'center' },
  content: { padding: 18, gap: 18, paddingBottom: 28 },
  row: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, alignItems: 'center' },
  tabs: { flexDirection: 'row', padding: 4, borderRadius: 14, backgroundColor: '#F0F2F5', gap: 4 },
  tab: { flex: 1, minHeight: 44, borderRadius: 10, alignItems: 'center', justifyContent: 'center', padding: 8 },
  activeTab: { backgroundColor: '#fff', boxShadow: '0px 2px 6px rgba(0,20,46,0.08)' },
  tabText: { fontFamily: fonts.bold, fontSize: 14, color: '#00142E' },
  card: { padding: 16, backgroundColor: '#FAFBFD', borderRadius: 18, borderWidth: 1, borderColor: '#E7EBF1', gap: 12 },
  heading: { fontFamily: fonts.bold, fontSize: 17, color: '#00142E' },
  sectionTitle: { fontFamily: fonts.title, fontSize: 23, color: '#00142E' },
  text: { fontFamily: fonts.body, fontSize: 14, lineHeight: 21, color: '#6B7787' },
  error: { fontFamily: fonts.semibold, fontSize: 14, color: '#B42318' },
  success: { fontFamily: fonts.semibold, fontSize: 14, color: '#0562D2' },
  choice: { padding: 14, borderRadius: 14, borderWidth: 1, borderColor: '#DEE5EE', backgroundColor: '#fff' },
  chosen: { borderColor: '#0562D2', backgroundColor: '#EDF4FC' },
  choiceCard: { padding: 20, gap: 10, borderWidth: 1, borderColor: '#E2E7ED', backgroundColor: '#F9FBFD', borderRadius: 18 },
  choiceTitle: { fontFamily: fonts.bold, fontSize: 17, color: '#00142E', marginTop: 4 },
  image: { width: '100%', height: 180, resizeMode: 'contain', borderRadius: 16 },
});
