import { StyleSheet } from 'react-native';
import { fonts } from '../../theme/typography';
export default StyleSheet.create({
  screen: { backgroundColor: '#F8FAFC' },
  screenContent: { padding: 0, paddingBottom: 0, gap: 0 },
  top: { paddingTop: 36, paddingBottom: 18 },
  intro: { marginBottom: 30 },
  eyebrow: { fontFamily: fonts.bold, fontSize: 10, letterSpacing: 2.4, color: '#0562D2' },
  title: { fontFamily: fonts.title, fontSize: 52, lineHeight: 58, letterSpacing: -1, color: '#00142E', marginTop: 8 },
  smallTitle: { fontSize: 44, lineHeight: 50 },
  description: { fontFamily: fonts.body, fontSize: 14, lineHeight: 23, color: '#687482', marginTop: 18, maxWidth: 600 },
  controls: { gap: 10 },
  searchBox: { minHeight: 56, borderRadius: 999, flexDirection: 'row', alignItems: 'center', paddingLeft: 16, paddingRight: 8, gap: 12, backgroundColor: '#fff', boxShadow: 'inset 3px 3px 8px rgba(0,20,46,0.07), 0px 5px 18px rgba(0,20,46,0.03)' },
  searchInput: { flex: 1, minWidth: 0, minHeight: 54, paddingVertical: 12, fontFamily: fonts.body, fontSize: 13, color: '#00142E' },
  clearIcon: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
  filterRow: { gap: 10, marginTop: 4 },
  filterField: { minHeight: 52, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 15, paddingVertical: 7, borderWidth: 1, borderColor: 'rgba(0,20,46,0.08)', borderRadius: 15, backgroundColor: '#fff' },
  field: { flex: 1, minWidth: 0 },
  fieldLabel: { fontFamily: fonts.bold, fontSize: 9, letterSpacing: 1, color: '#7D8793', textTransform: 'uppercase' },
  fieldInput: { fontFamily: fonts.body, fontSize: 14, padding: 0, paddingTop: 2, color: '#00142E' },
  chips: { marginTop: 18, gap: 8 },
  chipLabel: { fontFamily: fonts.bold, fontSize: 10, color: '#7D8793', letterSpacing: 1 },
  wrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: { minHeight: 44, maxWidth: '100%', borderRadius: 22, backgroundColor: '#EEF1F5', paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 10 },
  chipText: { flexShrink: 1, fontFamily: fonts.semibold, fontSize: 12, color: '#526176' },
  error: { marginTop: 12, fontFamily: fonts.semibold, fontSize: 14, color: '#B33A3A', backgroundColor: '#FAECEF', padding: 12, borderRadius: 14 },
  notice: { marginTop: 12, fontFamily: fonts.semibold, fontSize: 14, color: '#228B4E', backgroundColor: '#EBF7EF', padding: 12, borderRadius: 14 },
  resultsHeader: { marginTop: 50, paddingTop: 18, borderTopWidth: 1, borderTopColor: 'rgba(0,20,46,0.12)', flexDirection: 'row', alignItems: 'flex-end', gap: 14 },
  sectionLabel: { fontFamily: fonts.bold, fontSize: 9, letterSpacing: 2, color: '#8994A2', marginBottom: 9 },
  resultsTitle: { fontFamily: fonts.title, fontSize: 24, lineHeight: 28, color: '#00142E' },
  count: { fontFamily: fonts.bold, fontSize: 10, letterSpacing: 0.5, color: '#8994A2', paddingBottom: 3 },
  list: { paddingHorizontal: 20, paddingBottom: 120, width: '100%', maxWidth: 720, alignSelf: 'center' },
  separator: { height: 16 },
});
