import { useEffect, useState } from 'react';
import { ImageBackground, KeyboardAvoidingView, Platform, Text, View } from 'react-native';
import * as Google from 'expo-auth-session/providers/google';
import * as WebBrowser from 'expo-web-browser';
import { GoogleAuthProvider, signInWithCredential } from 'firebase/auth';
import FormField from '../../components/FormField'; import AppButton from '../../components/AppButton';
import { login, loginWithGoogle } from '../../services/authService'; import { auth } from '../../services/firebase'; import { useAuth } from '../../context/AuthContext'; import { isValidEmail } from '../../utils/validators'; import styles from './styles';
WebBrowser.maybeCompleteAuthSession();
export default function LoginScreen({navigation}){const {establish}=useAuth(); const [email,setEmail]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState('');const[loading,setLoading]=useState(false);
 const [request,response,promptAsync]=Google.useIdTokenAuthRequest({webClientId:process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID,androidClientId:process.env.EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID,iosClientId:process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID});
 async function finish(result){if(result.requiresTwoFactor){navigation.navigate('TwoFactor',{challengeToken:result.challengeToken});return;}await establish(result)}
 async function submit(){if(!isValidEmail(email)||!password){setError('Informe um e-mail válido e sua senha.');return;}setLoading(true);setError('');try{await finish(await login(email.trim(),password));}catch(e){setError(e.message||'Usuário ou senha incorretos.')}finally{setLoading(false)}}
 useEffect(()=>{if(response?.type!=='success')return; const idToken=response.params?.id_token; if(!idToken)return; (async()=>{setLoading(true);setError('');try{const credential=GoogleAuthProvider.credential(idToken);await signInWithCredential(auth,credential);await finish(await loginWithGoogle(idToken));}catch(e){setError(e.message||'Não foi possível entrar com Google.')}finally{setLoading(false)}})()},[response]);
 return <KeyboardAvoidingView style={styles.page} behavior={Platform.OS==='ios'?'padding':undefined}><View style={styles.shell}><ImageBackground source={{uri:'https://wallpapercave.com/wp/wp12639722.jpg'}} style={styles.hero} imageStyle={styles.heroImage}><View style={styles.overlay}/><View style={styles.heroCopy}><Text style={styles.kicker}>BUSINESS COMPETITIVE</Text><Text style={styles.heroTitle}>INTELIGÊNCIA{`\n`}PARA IR ALÉM.</Text></View></ImageBackground><View style={styles.form}><Text style={styles.formKicker}>BEYOND COMPARE INTELLIGENCE</Text><Text style={styles.title}>ENTRE NO BCI</Text><Text style={styles.subtitle}>Pesquisa competitiva, comparação e inteligência automotiva em um só lugar.</Text><FormField label="E-mail" value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address"/><FormField label="Senha" value={password} onChangeText={setPassword} secureTextEntry/>{error?<Text style={styles.error}>{error}</Text>:null}<AppButton title="Entrar" onPress={submit} loading={loading}/><AppButton title="Continuar com Google" variant="secondary" disabled={!request||loading} onPress={()=>promptAsync()}/><Text style={styles.link} onPress={()=>navigation.navigate('ResetPassword')}>Esqueci minha senha</Text><Text style={styles.footer}>Ainda não tem conta? <Text style={styles.linkStrong} onPress={()=>navigation.navigate('Register')}>Criar conta</Text></Text></View></View></KeyboardAvoidingView>}
