import { StyleSheet } from 'react-native';
import { fonts } from '../../theme/typography';

const navy = '#00142E';
const blue = '#0562D2';
const border = 'rgba(0,20,46,0.09)';
export default StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F7F7F5' },
  content: { paddingHorizontal: 16 },
  container: { width: '100%', maxWidth: 800, alignSelf: 'center', gap: 28 },
  pressed: { opacity: 0.72 },
  topbarRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 },
  topbarActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  topActionCaption: { width: 'auto', paddingHorizontal: 16 },
  importedActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 8 },
  dangerLabel: { color: '#A43737' },
  heroDescription: { fontFamily: fonts.body, fontSize: 14, lineHeight: 24, color: '#617080', marginTop: 4 },
  specCell: { flexGrow: 1, flexBasis: '46%', minWidth: 125, borderRadius: 18, overflow: 'hidden', backgroundColor: navy, boxShadow: '0px 8px 20px rgba(0,20,46,0.12)' },
  specMeta: { fontFamily: fonts.body, fontSize: 10, lineHeight: 15, color: '#B9C8DB', marginTop: 5 },
  specSources: { padding: 12, backgroundColor: '#fff' },
  technicalEyebrow: { fontFamily: fonts.bold, fontSize: 10, letterSpacing: 2.4, color: '#8190A0' },
  legendTitle: { fontFamily: fonts.bold, fontSize: 11, letterSpacing: 0.5, color: navy },
  sourcesButton: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 8, minHeight: 44, paddingHorizontal: 12, borderRadius: 999, backgroundColor: '#F0F2F5' },
  sourcesButtonLabel: { fontFamily: fonts.bold, fontSize: 11, color: navy },
  legendItems: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, borderTopWidth: 1, borderTopColor: border, paddingTop: 14 },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  legendPill: { fontFamily: fonts.bold, fontSize: 10, paddingHorizontal: 8, paddingVertical: 5, borderRadius: 999 },
  legendCaption: { fontFamily: fonts.body, fontSize: 10, color: '#68778A' },
  subsectionTitle: { fontFamily: fonts.bold, fontSize: 10, letterSpacing: 2, color: '#8190A0', marginTop: 20, marginBottom: 2 },
  accordionGroup: { borderWidth: 1, borderColor: border, borderRadius: 22, backgroundColor: '#fff', paddingHorizontal: 18, boxShadow: '0px 9px 28px rgba(0,20,46,0.035)' },
  accordionDivider: { borderTopWidth: 1, borderTopColor: border },
  technicalValue: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: 8 },
  analysisEyebrow: { fontFamily: fonts.bold, fontSize: 10, letterSpacing: 2, color: '#8ABAF7' },
  analysisTitle: { fontFamily: fonts.title, fontSize: 32, lineHeight: 36, color: '#fff' },
  analysisDescription: { fontFamily: fonts.body, fontSize: 13, lineHeight: 21, color: '#B7C3D2' },
  analysisCardTitle: { fontFamily: fonts.bold, fontSize: 12, letterSpacing: 1, textTransform: 'uppercase', color: '#fff' },
  analysisText: { fontFamily: fonts.body, fontSize: 13, lineHeight: 21, color: '#E0E7F0' },
  bestUseText: { fontFamily: fonts.bold, fontSize: 17, lineHeight: 24, color: '#fff' },
  analysisFeedback: { minHeight: 110, padding: 18, alignItems: 'center', justifyContent: 'center', borderRadius: 18, backgroundColor: 'rgba(255,255,255,0.055)', gap: 10 },
  analysisError: { fontFamily: fonts.body, fontSize: 13, lineHeight: 21, color: '#FFBCAE' },
  analysisDisclaimer: { fontFamily: fonts.body, fontSize: 11, lineHeight: 18, color: '#B7C3D2' },
  generateButton: { minHeight: 44, paddingHorizontal: 16, paddingVertical: 12, borderRadius: 999, borderWidth: 1, borderColor: 'rgba(255,255,255,0.2)', backgroundColor: 'rgba(255,255,255,0.1)', alignSelf: 'flex-start' },
  generateLabel: { fontFamily: fonts.bold, fontSize: 11, letterSpacing: 0.6, textTransform: 'uppercase', color: '#fff' },
  flex: { flex: 1 }, disabled: { opacity: 0.45 },
  topbar: { gap: 10 },
  topAction: { width: 44, minHeight: 44, borderRadius: 999, backgroundColor: 'rgba(0,20,46,0.055)', alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8 },
  circle: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff', borderWidth: 1, borderColor: border },
  activeCircle: { backgroundColor: navy },
  actionLabel: { fontFamily: fonts.bold, fontSize: 11, letterSpacing: 0.8, color: navy, textTransform: 'uppercase' },
  hero: { gap: 25 },
  preview: { minHeight: 230, borderRadius: 22, padding: 20, borderWidth: 1, borderColor: 'rgba(0,20,46,0.07)', backgroundColor: 'rgba(255,255,255,0.85)', boxShadow: '0px 12px 35px rgba(0,20,46,0.045)' },
  image: { width: '100%', height: 210 },
  imagePlaceholder: { height: 190, alignItems: 'center', justifyContent: 'center', gap: 12 },
  imageBadges: { position: 'absolute', left: 14, top: 14, right: 14, flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  pill: { fontFamily: fonts.bold, fontSize: 10, color: blue, backgroundColor: '#EAF2FC', borderRadius: 999, paddingVertical: 6, paddingHorizontal: 10, letterSpacing: 0.8 },
  heroCopy: { gap: 12 },
  eyebrow: { fontFamily: fonts.bold, fontSize: 11, letterSpacing: 2, color: blue, textTransform: 'uppercase' },
  heroTitle: { fontFamily: fonts.title, fontSize: 46, lineHeight: 49, letterSpacing: -1, color: navy, textTransform: 'uppercase' },
  identityRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 12 },
  category: { fontFamily: fonts.semibold, fontSize: 12, color: navy, borderRadius: 999, paddingHorizontal: 12, paddingVertical: 6, backgroundColor: '#E9EDF2' },
  body: { fontFamily: fonts.body, fontSize: 15, lineHeight: 24, color: '#4C5B6D' },
  muted: { fontFamily: fonts.body, fontSize: 12, lineHeight: 18, color: '#68778A', flexShrink: 1 },
  confidenceRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 8 },
  specGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 8 },
  specCard: { flex: 1, minHeight: 156, padding: 15, backgroundColor: navy, gap: 4 },
  specIcon: { width: 34, height: 34, borderRadius: 10, backgroundColor: 'rgba(255,255,255,0.09)', alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  specLabel: { fontFamily: fonts.bold, fontSize: 9, letterSpacing: 1.8, textTransform: 'uppercase', color: '#ADB9C9' },
  specValue: { fontFamily: fonts.bold, fontSize: 16, lineHeight: 21, color: '#fff' },
  evidence: { gap: 7, alignItems: 'flex-start', marginTop: 2 },
  aiTag: { fontFamily: fonts.semibold, fontSize: 11, color: blue, backgroundColor: '#EAF2FC', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 9, alignSelf: 'flex-start' },
  conflict: { fontFamily: fonts.semibold, fontSize: 11, color: '#955114' },
  sourceLink: { flexDirection: 'row', alignItems: 'center', gap: 5, minHeight: 36, maxWidth: '100%' },
  sourceText: { fontFamily: fonts.body, color: blue, fontSize: 12, flexShrink: 1 },
  alternative: { borderLeftWidth: 2, borderLeftColor: '#E6C393', paddingLeft: 8, gap: 4 },
  technical: { gap: 12, marginTop: 8 },
  sectionHeading: { gap: 8, marginBottom: 6 },
  sectionTitle: { fontFamily: fonts.title, color: navy, fontSize: 36, lineHeight: 40, textTransform: 'uppercase' },
  legend: { backgroundColor: 'rgba(255,255,255,0.8)', borderRadius: 22, borderWidth: 1, borderColor: border, padding: 18, gap: 14, boxShadow: '0px 8px 24px rgba(0,20,46,0.035)' },
  legendHeader: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  subheading: { fontFamily: fonts.bold, fontSize: 14, color: navy },
  accordion: { backgroundColor: 'transparent' },
  accordionTrigger: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 20, minHeight: 66, gap: 12 },
  accordionTitle: { fontFamily: fonts.bold, color: navy, fontSize: 14, flex: 1 },
  accordionContent: { paddingBottom: 18, gap: 0 },
  technicalRow: { borderTopWidth: 1, borderTopColor: 'rgba(0,20,46,0.05)', paddingVertical: 12, gap: 8 },
  rowLabel: { fontFamily: fonts.body, fontSize: 12, color: '#718094', flexGrow: 1, flexBasis: '42%' },
  rowValue: { fontFamily: fonts.semibold, fontSize: 14, color: navy, flexShrink: 1, flexBasis: '52%' },
  sourcesPanel: { paddingTop: 14, borderTopWidth: 1, borderTopColor: border, gap: 8 },
  analysis: { padding: 20, borderRadius: 24, backgroundColor: '#071B35', marginTop: 14, gap: 12, boxShadow: '0px 16px 32px rgba(0,20,46,0.10)' },
  analysisHeading: { gap: 8 },
  analysisGrid: { gap: 11, marginTop: 14 },
  analysisCard: { padding: 18, borderRadius: 17, backgroundColor: 'rgba(255,255,255,0.055)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.11)', gap: 10 },
  bestUse: { backgroundColor: blue, borderColor: blue },
  feedback: { padding: 18, gap: 12, borderRadius: 18, backgroundColor: '#EDF2F8' },
  error: { fontFamily: fonts.body, fontSize: 14, lineHeight: 21, color: '#A43737' },
  empty: { paddingVertical: 48, gap: 20 },
  toast: { position: 'absolute', left: 24, right: 24, padding: 16, borderRadius: 18, backgroundColor: '#E8F5EE', borderColor: '#B5DCCA', borderWidth: 1, boxShadow: '0px 6px 20px rgba(0,20,46,0.1)' },
  toastText: { fontFamily: fonts.bold, fontSize: 14, textAlign: 'center', color: '#176544' },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,20,46,0.45)', padding: 20, justifyContent: 'center', alignItems: 'center' },
  exportSheet: { width: '100%', maxWidth: 520, maxHeight: '95%', backgroundColor: '#fff', borderRadius: 26, overflow: 'hidden' },
  exportContent: { padding: 24, gap: 18 },
  formats: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  format: { flexGrow: 1, flexBasis: '44%', minHeight: 54, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: border, borderRadius: 14 },
  formatSelected: { borderColor: blue, backgroundColor: '#EAF2FC' },
  separatorOptions: { gap: 6 },
  separatorOption: { flexDirection: 'row', alignItems: 'center', gap: 10, minHeight: 44 },
});
