import { StyleSheet } from 'react-native';
import { fonts } from '../../theme/typography';

const navy = '#00142E';
const blue = '#0562D2';
const border = 'rgba(0,20,46,0.09)';
export default StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F7F8FA' },
  content: { paddingHorizontal: 16 },
  container: { width: '100%', maxWidth: 800, alignSelf: 'center', gap: 24 },
  flex: { flex: 1 }, disabled: { opacity: 0.45 },
  topbar: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'flex-start', gap: 6, borderBottomWidth: 1, borderBottomColor: border, paddingBottom: 18 },
  topAction: { flexGrow: 1, flexBasis: 44, alignItems: 'center', gap: 5, maxWidth: 86 },
  circle: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff', borderWidth: 1, borderColor: border },
  activeCircle: { backgroundColor: '#EAF2FC', borderColor: '#BFDAFB' },
  actionLabel: { fontFamily: fonts.semibold, fontSize: 10, color: navy, textAlign: 'center' },
  hero: { gap: 24 },
  preview: { minHeight: 245, borderRadius: 26, padding: 18, borderWidth: 1, borderColor: border, backgroundColor: '#fff', boxShadow: '0px 10px 28px rgba(0,20,46,0.04)' },
  image: { width: '100%', height: 220 },
  imagePlaceholder: { height: 220, alignItems: 'center', justifyContent: 'center', gap: 12 },
  imageBadges: { position: 'absolute', left: 14, top: 14, right: 14, flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  pill: { fontFamily: fonts.bold, fontSize: 10, color: blue, backgroundColor: '#EAF2FC', borderRadius: 999, paddingVertical: 6, paddingHorizontal: 10, letterSpacing: 0.8 },
  heroCopy: { gap: 14 },
  eyebrow: { fontFamily: fonts.bold, fontSize: 11, letterSpacing: 2, color: blue, textTransform: 'uppercase' },
  heroTitle: { fontFamily: fonts.title, fontSize: 46, lineHeight: 52, letterSpacing: -0.6, color: navy, textTransform: 'uppercase' },
  identityRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 12 },
  year: { fontFamily: fonts.title, fontSize: 30, color: navy },
  category: { fontFamily: fonts.semibold, fontSize: 12, color: navy, borderRadius: 999, paddingHorizontal: 12, paddingVertical: 6, backgroundColor: '#E9EDF2' },
  body: { fontFamily: fonts.body, fontSize: 15, lineHeight: 24, color: '#4C5B6D' },
  muted: { fontFamily: fonts.body, fontSize: 12, lineHeight: 18, color: '#68778A', flexShrink: 1 },
  confidenceRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 8 },
  sourceToggle: { alignSelf: 'flex-end', minHeight: 44, justifyContent: 'center', marginBottom: -18 },
  linkLabel: { fontFamily: fonts.bold, fontSize: 12, color: blue },
  specGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  specCard: { flexGrow: 1, flexBasis: '46%', minWidth: 130, borderRadius: 20, borderWidth: 1, borderColor: border, padding: 16, backgroundColor: '#fff', gap: 9 },
  specIcon: { width: 36, height: 36, borderRadius: 11, backgroundColor: '#EEF4FC', alignItems: 'center', justifyContent: 'center', marginBottom: 8 },
  specLabel: { fontFamily: fonts.bold, fontSize: 10, letterSpacing: 1.3, textTransform: 'uppercase', color: '#728094' },
  specValue: { fontFamily: fonts.bold, fontSize: 19, color: navy },
  evidence: { gap: 7, alignItems: 'flex-start', marginTop: 2 },
  aiTag: { fontFamily: fonts.semibold, fontSize: 11, color: blue, backgroundColor: '#EAF2FC', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 9, alignSelf: 'flex-start' },
  conflict: { fontFamily: fonts.semibold, fontSize: 11, color: '#955114' },
  sourceLink: { flexDirection: 'row', alignItems: 'center', gap: 5, minHeight: 36, maxWidth: '100%' },
  sourceText: { fontFamily: fonts.body, color: blue, fontSize: 12, flexShrink: 1 },
  alternative: { borderLeftWidth: 2, borderLeftColor: '#E6C393', paddingLeft: 8, gap: 4 },
  technical: { gap: 10, marginTop: 14 },
  sectionHeading: { gap: 10, marginBottom: 12 },
  sectionTitle: { fontFamily: fonts.title, color: navy, fontSize: 30, lineHeight: 36 },
  legend: { backgroundColor: '#fff', borderRadius: 20, borderWidth: 1, borderColor: border, padding: 18, gap: 12, marginBottom: 8 },
  legendHeader: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  legendText: { fontFamily: fonts.body, fontSize: 11, lineHeight: 18, color: '#68778A', borderTopWidth: 1, borderTopColor: border, paddingTop: 12 },
  subheading: { fontFamily: fonts.bold, fontSize: 14, color: navy },
  accordion: { borderWidth: 1, borderColor: border, borderRadius: 18, backgroundColor: '#fff', overflow: 'hidden' },
  accordionOpen: { borderColor: '#C6D8EF' },
  accordionTrigger: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 18, minHeight: 62, gap: 12 },
  accordionTitle: { fontFamily: fonts.bold, color: navy, fontSize: 15, flex: 1 },
  accordionContent: { paddingHorizontal: 18, paddingBottom: 18, gap: 4 },
  technicalRow: { borderTopWidth: 1, borderTopColor: border, paddingVertical: 14, gap: 5 },
  rowLabel: { fontFamily: fonts.body, fontSize: 12, color: '#718094' },
  rowValue: { fontFamily: fonts.semibold, fontSize: 16, color: navy },
  sourcesPanel: { padding: 18, backgroundColor: '#EEF3F9', borderRadius: 18, gap: 10 },
  analysis: { borderTopWidth: 1, borderTopColor: border, paddingTop: 30, marginTop: 16, gap: 14 },
  analysisHeading: { flexDirection: 'row', gap: 14, alignItems: 'center' },
  analysisIcon: { width: 52, height: 52, borderRadius: 18, backgroundColor: navy, alignItems: 'center', justifyContent: 'center' },
  analysisGrid: { gap: 12, marginTop: 8 },
  analysisCard: { padding: 20, borderRadius: 20, backgroundColor: '#fff', borderWidth: 1, borderColor: border, gap: 12 },
  bestUse: { backgroundColor: '#EAF2FC', borderColor: '#C5DBF5' },
  feedback: { padding: 18, gap: 12, borderRadius: 18, backgroundColor: '#EDF2F8' },
  error: { fontFamily: fonts.body, fontSize: 14, lineHeight: 21, color: '#A43737' },
  empty: { paddingVertical: 48, gap: 20 },
  toast: { position: 'absolute', left: 24, right: 24, padding: 16, borderRadius: 18, backgroundColor: '#E8F5EE', borderColor: '#B5DCCA', borderWidth: 1, boxShadow: '0px 6px 20px rgba(0,20,46,0.1)' },
  toastText: { fontFamily: fonts.bold, fontSize: 14, textAlign: 'center', color: '#176544' },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,20,46,0.45)', padding: 20, justifyContent: 'center', alignItems: 'center' },
  exportSheet: { width: '100%', maxWidth: 520, maxHeight: '95%', backgroundColor: '#fff', borderRadius: 26, overflow: 'hidden' },
  exportContent: { padding: 24, gap: 18 },
  formats: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  format: { flexGrow: 1, flexBasis: '44%', minHeight: 54, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: border, borderRadius: 14 },
  formatSelected: { borderColor: blue, backgroundColor: '#EAF2FC' },
  separatorOptions: { gap: 6 },
  separatorOption: { flexDirection: 'row', alignItems: 'center', gap: 10, minHeight: 44 },
});
