import { StyleSheet } from 'react-native';
import { fonts } from '../../theme/typography';
const navy = '#00142E';
const blue = '#0562D2';
const border = 'rgba(0,20,46,0.12)';
export default StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F7F7F5' },
  content: { paddingHorizontal: 24 },
  container: { width: '100%', maxWidth: 800, alignSelf: 'center' },
  flex: { flex: 1 },
  pressed: { opacity: 0.75 },
  hero: { marginBottom: 26 },
  heroCopy: { gap: 18 },
  eyebrow: { fontFamily: fonts.bold, color: blue, fontSize: 10, lineHeight: 17, letterSpacing: 2, marginRight: 58 },
  heroTitle: { fontFamily: fonts.title, color: navy, letterSpacing: -1, textTransform: 'uppercase', marginRight: 58 },
  heroDescription: { fontFamily: fonts.body, fontSize: 14, lineHeight: 23, color: '#5D6875', maxWidth: 480 },
  heroActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 6 },
  heroButton: { flexGrow: 1, flexBasis: 136, minHeight: 50, paddingHorizontal: 14, paddingVertical: 12, borderRadius: 999, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: navy, boxShadow: '0px 8px 16px rgba(0,20,46,0.16)' },
  secondaryButton: { backgroundColor: '#fff', boxShadow: '0px 6px 16px rgba(0,20,46,0.09)' },
  buttonLabel: { fontFamily: fonts.bold, fontSize: 11, letterSpacing: 0.6, textTransform: 'uppercase', color: '#fff' },
  secondaryLabel: { color: navy },
  carStage: { height: 280, marginTop: 10, marginHorizontal: -24, overflow: 'hidden', justifyContent: 'center' },
  carGlow: { position: 'absolute', bottom: 45, right: 8, width: '80%', height: 115, borderRadius: 999, backgroundColor: 'rgba(0,20,46,0.035)', boxShadow: '0px 0px 45px 12px rgba(0,20,46,0.025)' },
  heroCar: { width: '112%', height: 235, marginLeft: 10 },
  carFallback: { height: 235, alignItems: 'center', justifyContent: 'center', gap: 12 },
  carouselControls: { position: 'absolute', bottom: 0, right: 20, flexDirection: 'row', alignItems: 'center', gap: 2 },
  carouselButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
  carouselCount: { fontFamily: fonts.bold, fontSize: 10, letterSpacing: 1.8, color: navy },
  carouselTotal: { color: '#8390A0' },
  section: { marginBottom: 56 },
  sectionHeading: { flexDirection: 'row', alignItems: 'center', gap: 16, marginBottom: 22 },
  sectionLabel: { fontFamily: fonts.bold, fontSize: 10, lineHeight: 16, letterSpacing: 2.2, color: '#6A7888', flexShrink: 1 },
  sectionLine: { height: 1, backgroundColor: border, flexGrow: 1, minWidth: 22 },
  metrics: { flexDirection: 'row', flexWrap: 'wrap', borderTopWidth: 1, borderBottomWidth: 1, borderColor: border },
  metric: { width: '50%', minHeight: 130, paddingVertical: 22, paddingHorizontal: 18, justifyContent: 'center', gap: 10 },
  metricRightBorder: { borderRightWidth: 1, borderRightColor: border },
  metricBottomBorder: { borderBottomWidth: 1, borderBottomColor: border },
  metricValue: { fontFamily: fonts.title, fontSize: 44, lineHeight: 48, color: navy },
  metricLabel: { fontFamily: fonts.bold, fontSize: 10, lineHeight: 15, letterSpacing: 1.3, color: '#687687' },
  highlights: { gap: 14 },
  highlight: { minHeight: 190, padding: 25, borderRadius: 26, backgroundColor: '#fff', borderWidth: 1, borderColor: 'rgba(0,20,46,0.09)', justifyContent: 'space-between', gap: 18, boxShadow: '0px 8px 20px rgba(0,20,46,0.04)' },
  featured: { backgroundColor: navy, borderColor: navy, boxShadow: '0px 12px 26px rgba(0,20,46,0.12)' },
  cardCategory: { fontFamily: fonts.bold, color: '#718092', fontSize: 10, letterSpacing: 2, textTransform: 'uppercase' },
  cardTitle: { fontFamily: fonts.title, fontSize: 31, lineHeight: 35, color: navy, textTransform: 'uppercase', marginTop: 16, marginBottom: 10 },
  cardDescription: { fontFamily: fonts.body, fontSize: 14, lineHeight: 22, color: '#647183' },
  cardArrow: { alignSelf: 'flex-end' },
  inverse: { color: '#fff' },
  inverseMuted: { color: '#B7C5D8' },
  body: { fontFamily: fonts.body, fontSize: 14, lineHeight: 22, color: '#687687' },
  muted: { fontFamily: fonts.body, fontSize: 12, lineHeight: 18, color: '#687687' },
  coverageDescription: { fontFamily: fonts.body, fontSize: 13, lineHeight: 21, color: '#687687', marginBottom: 22 },
  coverageList: { gap: 24 },
  coverageHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, marginBottom: 10 },
  coverageName: { fontFamily: fonts.bold, fontSize: 14, color: navy, flexShrink: 1 },
  coverageValue: { fontFamily: fonts.body, fontSize: 13, color: '#687687' },
  coverageTrack: { height: 8, borderRadius: 999, backgroundColor: 'rgba(0,20,46,0.08)', overflow: 'hidden' },
  coverageFill: { height: '100%', borderRadius: 999, backgroundColor: '#2E63C7' },
  empty: { gap: 8, paddingVertical: 8 },
  emptyTitle: { fontFamily: fonts.bold, fontSize: 17, color: navy },
  monitoringHeading: { flexDirection: 'row', gap: 16, alignItems: 'center' },
  monitoringTitle: { fontFamily: fonts.title, fontSize: 27, lineHeight: 32, color: navy, flex: 1 },
  monitoringDescription: { fontFamily: fonts.body, fontSize: 13, color: '#687687', marginTop: 8, marginBottom: 20 },
  alertCard: { flexDirection: 'row', gap: 14, padding: 22, borderRadius: 22, backgroundColor: '#E6ECF6', borderWidth: 1, borderColor: 'rgba(0,20,46,0.05)' },
  alertDot: { width: 9, height: 9, borderRadius: 9, backgroundColor: '#D96B58', marginTop: 7 },
  alertTitle: { fontFamily: fonts.bold, fontSize: 15, lineHeight: 22, color: navy, marginBottom: 6 },
  reviewLink: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 16, minHeight: 32 },
  linkText: { fontFamily: fonts.bold, fontSize: 13, color: blue },
  alertsEmpty: { flexDirection: 'row', alignItems: 'center', gap: 14, padding: 20, backgroundColor: '#EDF3F0', borderWidth: 1, borderColor: 'rgba(43,143,108,0.08)', borderRadius: 22 },
  checkCircle: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(43,143,108,0.10)' },
  allClear: { fontFamily: fonts.bold, fontSize: 16, lineHeight: 22, color: '#1D5D48', marginBottom: 4 },
  activityList: { borderTopWidth: 1, borderTopColor: border },
  activityRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 18, borderBottomWidth: 1, borderBottomColor: border },
  activityIcon: { width: 40, height: 40, borderRadius: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(0,20,46,0.05)' },
  activityType: { fontFamily: fonts.bold, color: '#8190A0', fontSize: 9, letterSpacing: 1.5, marginBottom: 5 },
  activityTitle: { fontFamily: fonts.bold, fontSize: 14, lineHeight: 20, color: navy },
  activityDate: { fontFamily: fonts.body, fontSize: 11, color: '#687687', marginTop: 5 },
  footer: { paddingTop: 24, borderTopWidth: 1, borderTopColor: border, gap: 6 },
  footerText: { fontFamily: fonts.body, fontSize: 11, lineHeight: 17, color: '#7C8795' },
  errorBanner: { borderRadius: 16, backgroundColor: '#FFF3E9', padding: 16, marginBottom: 28, gap: 6 },
  errorText: { fontFamily: fonts.body, color: '#8C5328', fontSize: 13 },
  retry: { alignSelf: 'flex-start', minHeight: 44, justifyContent: 'center' },
});
